# Generated by Django 4.2.23 on 2025-07-11 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snapapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
