# Generated by Django 4.2.23 on 2025-07-16 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('snapapp', '0002_delete_customuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='EbayItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ebay_id', models.CharField(max_length=50, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('condition', models.CharField(max_length=50)),
                ('image_url', models.URLField()),
                ('item_url', models.URLField()),
                ('seller_username', models.CharField(max_length=100)),
                ('category_id', models.CharField(blank=True, max_length=20)),
                ('category_name', models.CharField(blank=True, max_length=100)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('shipping_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
